- name: Load Maven
  ansible.builtin.import_role:
    name: common
    tasks_from: maven

- name: Install MYSQL client
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: Load Schema
  ansible.builtin.shell: mysql -h mysql-dev.chaithanya.online -uroot -p$1 < /app/db/schema.sql

- name: Load App User
  ansible.builtin.shell: mysql -h mysql-dev.chaithanya.online -uroot -p$1 < /app/db/app-user.sql

- name: Load master-data
  ansible.builtin.shell: mysql -h mysql-dev.chaithanya.online -uroot -p$1 < /app/db/master-data.sql