#- name: Load Maven
#  ansible.builtin.import_role:
#    name: common
#    tasks_from: maven
#
#- name: Install MYSQL client
#  ansible.builtin.dnf:
#    name: mysql
#    state: installed
#
#- name: Load Schema
#  ansible.builtin.shell: mysql -h mysql-dev.chaithanya.online -u{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/shipping:DB_USER token={{ token }} url=http://vault-internal.chaithanya.online:8200') }} -p{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/shipping:DB_PASS token={{ token }} url=http://vault-internal.chaithanya.online:8200') }} < /app/db/{{item}}.sql
#  loop:
#    - schema
#    - app-user
#    - master-data


- name: Load Docker
  ansible.builtin.import_role:
    name: common
    tasks_from: docker