- name: Copy component service file
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest: /etc/systemd/system/{{component}}.service

- name: Start service
  ansible.builtin.systemd_service:
    daemon-reload: true
    enabled: true
    state: restarted
    name: "{{ component }}"


